import { Topbar } from '@/components/layout/Topbar'
import { Download, Share2, RefreshCw } from 'lucide-react'

const REPORT_SECTIONS = [
  {
    title: 'Anomaly Detection',
    color: '#3b82f6',
    items: [
      'Connection CONN-007 (Sharjah Industrial) shows 34% higher demand than comparable capacity peers — recommend capacity review.',
      'DIFC Tower (CONN-002) incurring fixed network charges on 3 inactive sub-meters — AED 1,840/month recoverable savings identified.',
    ],
  },
  {
    title: 'Contract Efficiency',
    color: '#f59e0b',
    items: [
      '3 connections operating at <40% of contracted capacity — potential for tariff reclassification saving estimated AED 4,200/month.',
      'RAK Free Zone meter upgrade required by Q2 2026 under FEWA smart meter mandate — recommend scheduling contractor Q1.',
    ],
  },
  {
    title: 'Budget & Forecast',
    color: '#10b981',
    items: [
      'On current trajectory, portfolio will reach AED 284K by year-end — 21% under annual budget of AED 360K.',
      'Q3 peak demand charges (summer AC load) will likely increase August billing by 8–12% — pre-approve budget buffer.',
    ],
  },
  {
    title: 'ESG & Compliance',
    color: '#8b5cf6',
    items: [
      'Masdar City site solar offset: 142 tCO₂ avoided YTD — eligible for UAE green building certification credit renewal.',
      'All connections compliant with UAE Climate Action Law (2023) reporting requirements.',
    ],
  },
]

export default function Reports() {
  return (
    <div className="flex flex-col h-full overflow-hidden">
      <Topbar title="Reports" subtitle="AI-generated executive summaries" />
      <div className="flex-1 overflow-y-auto p-6">

        <div className="p-3 bg-accent/5 border border-accent/20 rounded-xl text-xs text-accent-hover mb-6 flex items-center gap-2">
          <RefreshCw size={12} /> AI-generated executive reports are auto-updated weekly. Last generated: today 06:00 GST.
        </div>

        <div className="card">
          <div className="flex items-center justify-between mb-6">
            <div>
              <h2 className="section-title">Portfolio Executive Summary — June 2025</h2>
              <p className="text-xs text-white/30 mt-1">Generated by Claude AI · 15 connections · UAE market context</p>
            </div>
            <div className="flex gap-2">
              <button className="btn-secondary flex items-center gap-1.5"><Download size={13} /> Export PDF</button>
              <button className="btn-secondary flex items-center gap-1.5"><Share2 size={13} /> Share</button>
            </div>
          </div>

          <div className="space-y-6">
            {REPORT_SECTIONS.map(section => (
              <div key={section.title}>
                <div className="flex items-center gap-2 mb-3">
                  <div className="w-1 h-4 rounded-full" style={{ background: section.color }} />
                  <h3 className="text-xs font-semibold uppercase tracking-wider" style={{ color: section.color }}>
                    {section.title}
                  </h3>
                </div>
                <div className="space-y-2 pl-3">
                  {section.items.map((item, i) => (
                    <div key={i} className="flex items-start gap-2.5 text-sm text-white/60 leading-relaxed">
                      <div className="w-1 h-1 rounded-full mt-2 flex-shrink-0" style={{ background: section.color, opacity: 0.6 }} />
                      {item}
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>

      </div>
    </div>
  )
}
