// Extended connections dataset for the Connections page
// Mirrors the layout of the reference screenshot (Aansluitingen)

export interface FullConnection {
  id: string
  product: 'Electricity' | 'Gas' | 'Water'
  client: string
  department: string
  name: string          // Naam aansluiting
  ean_code: string
  address: string
  postcode: string
  city: string
  cost_center: string
  status: 'Active' | 'Inactive' | 'Pending'
  supplier: string
  grid_operator: string
  measurement_company: string
  connection_type: string
  building: string
  market_segment: string
  monitoring: string
  characteristic: string
  usage_category: string
  tax_cluster: string
}

const C = 'Masdar City Group'

export const FULL_CONNECTIONS: FullConnection[] = [
  // ── Electricity ─────────────────────────────────────────────────────────────
  { id:'conn-001', product:'Electricity', client:C, department:'Real Estate',      name:'Business Bay Main',        ean_code:'971-4-BBY-882100', address:'Sheikh Zayed Rd 12',     postcode:'11211', city:'Dubai',          cost_center:'5801009-38001', status:'Active',  supplier:'DEWA',  grid_operator:'DEWA',  measurement_company:'DEWA Metering',  connection_type:'3x250A LV', building:'Tower A', market_segment:'Commercial', monitoring:'Smart', characteristic:'High Voltage', usage_category:'Office',    tax_cluster:'VAT-5' },
  { id:'conn-002', product:'Electricity', client:C, department:'Pumping Stations', name:'Pump BBY 1116',            ean_code:'971-4-BBY-882116', address:'Al Asayel St 85 116',    postcode:'11211', city:'Dubai',          cost_center:'9620607-782-33', status:'Active',  supplier:'DEWA',  grid_operator:'DEWA',  measurement_company:'DEWA Metering',  connection_type:'3x400A LV', building:'Pump House', market_segment:'Industrial', monitoring:'Smart', characteristic:'Standard', usage_category:'Pumping',   tax_cluster:'VAT-5' },
  { id:'conn-003', product:'Electricity', client:C, department:'Pumping Stations', name:'Pump BBY 1127',            ean_code:'971-4-BBY-882127', address:'Al Asayel St 156 127',   postcode:'11211', city:'Dubai',          cost_center:'9620607-782-33', status:'Active',  supplier:'DEWA',  grid_operator:'DEWA',  measurement_company:'DEWA Metering',  connection_type:'3x400A LV', building:'Pump House', market_segment:'Industrial', monitoring:'Smart', characteristic:'Standard', usage_category:'Pumping',   tax_cluster:'VAT-5' },
  { id:'conn-004', product:'Electricity', client:C, department:'Traffic & Roads',  name:'Camera Interchange 1',     ean_code:'971-4-BBY-946377', address:'Al Khail Rd 54 NST',     postcode:'11311', city:'Dubai',          cost_center:'000966',         status:'Active',  supplier:'DEWA',  grid_operator:'DEWA',  measurement_company:'DEWA Metering',  connection_type:'1x25A LV',  building:'Street Cabinet', market_segment:'Infrastructure', monitoring:'Smart', characteristic:'Low Load', usage_category:'Lighting',  tax_cluster:'VAT-0' },
  { id:'conn-005', product:'Electricity', client:C, department:'Pumping Stations', name:'Pump CVK 43',              ean_code:'971-4-BBY-832232', address:'Achterweg 4',            postcode:'11319', city:'Dubai',          cost_center:'9620608-782-33', status:'Active',  supplier:'DEWA',  grid_operator:'DEWA',  measurement_company:'DEWA Metering',  connection_type:'3x400A LV', building:'Pump Station', market_segment:'Industrial', monitoring:'Smart', characteristic:'Standard', usage_category:'Pumping',   tax_cluster:'VAT-5' },
  { id:'conn-006', product:'Electricity', client:C, department:'Construction',     name:'Fountain Admiraal',        ean_code:'971-4-DIF-316453', address:'Admiraal Pl 158 Nabij',  postcode:'11317', city:'Dubai',          cost_center:'60544401',       status:'Active',  supplier:'DEWA',  grid_operator:'DEWA',  measurement_company:'DEWA Metering',  connection_type:'1x63A LV',  building:'Public Space', market_segment:'Municipality', monitoring:'Basic', characteristic:'Standard', usage_category:'Water Feature', tax_cluster:'VAT-5' },
  { id:'conn-007', product:'Electricity', client:C, department:'Traffic & Roads',  name:'VRI Interchange North',    ean_code:'971-4-DIF-406659', address:'Admiraal Pl 158 Thv-vri',postcode:'11317', city:'Dubai',          cost_center:'P-30156870',     status:'Active',  supplier:'DEWA',  grid_operator:'DEWA',  measurement_company:'DEWA Metering',  connection_type:'1x35A LV',  building:'Street Cabinet', market_segment:'Infrastructure', monitoring:'Smart', characteristic:'Low Load', usage_category:'Traffic',   tax_cluster:'VAT-0' },
  { id:'conn-008', product:'Electricity', client:C, department:'Real Estate',      name:'Community Centre BBY',     ean_code:'971-4-BBY-362081', address:'Business Bay Sq 412',    postcode:'11317', city:'Dubai',          cost_center:'P-85001250',     status:'Active',  supplier:'DEWA',  grid_operator:'DEWA',  measurement_company:'DEWA Metering',  connection_type:'3x160A LV', building:'Community Hall', market_segment:'Commercial', monitoring:'Smart', characteristic:'Standard', usage_category:'Community', tax_cluster:'VAT-5' },
  { id:'conn-009', product:'Electricity', client:C, department:'Pumping Stations', name:'Pump 1015',                ean_code:'971-4-DIF-149804', address:'Ampere St 5 15-edison',  postcode:'11316', city:'Dubai',          cost_center:'9620606-782-33', status:'Active',  supplier:'DEWA',  grid_operator:'DEWA',  measurement_company:'DEWA Metering',  connection_type:'3x250A LV', building:'Pump House', market_segment:'Industrial', monitoring:'Smart', characteristic:'Standard', usage_category:'Pumping',   tax_cluster:'VAT-5' },
  { id:'conn-010', product:'Electricity', client:C, department:'Pumping Stations', name:'Pump 1001 RG Amstel',      ean_code:'971-4-DIF-152491', address:'Amstelwijckweg 0 A',     postcode:'11316', city:'Dubai',          cost_center:'9620606-782-33', status:'Active',  supplier:'DEWA',  grid_operator:'DEWA',  measurement_company:'DEWA Metering',  connection_type:'3x250A LV', building:'Pump House', market_segment:'Industrial', monitoring:'Smart', characteristic:'Standard', usage_category:'Pumping',   tax_cluster:'VAT-5' },
  { id:'conn-011', product:'Electricity', client:C, department:'Pumping Stations', name:'Pump CVK 50',              ean_code:'971-4-DIF-152477', address:'Amstelwijkweg 1 Nabij',  postcode:'11316', city:'Dubai',          cost_center:'9620608-782-33', status:'Active',  supplier:'DEWA',  grid_operator:'DEWA',  measurement_company:'DEWA Metering',  connection_type:'3x250A LV', building:'Pump House', market_segment:'Industrial', monitoring:'Smart', characteristic:'Standard', usage_category:'Pumping',   tax_cluster:'VAT-5' },
  { id:'conn-012', product:'Electricity', client:C, department:'Real Estate',      name:'DIFC Tower Main',          ean_code:'971-4-DIF-882200', address:'Gate Ave DIFC',          postcode:'50001', city:'Dubai',          cost_center:'DIFC-0012',      status:'Active',  supplier:'DEWA',  grid_operator:'DEWA',  measurement_company:'DEWA Metering',  connection_type:'3x400A LV', building:'Office Tower', market_segment:'Commercial', monitoring:'Smart', characteristic:'High Voltage', usage_category:'Office',    tax_cluster:'VAT-5' },
  { id:'conn-013', product:'Electricity', client:C, department:'Real Estate',      name:'Masdar HQ Main',           ean_code:'971-2-MAS-904100', address:'Masdar City Central',    postcode:'00000', city:'Abu Dhabi',      cost_center:'MAS-9041',       status:'Active',  supplier:'ADC',   grid_operator:'ADC',   measurement_company:'ADC Metering',   connection_type:'3x630A MV', building:'HQ Building', market_segment:'Commercial', monitoring:'Smart', characteristic:'High Voltage', usage_category:'Office',    tax_cluster:'VAT-5' },
  { id:'conn-014', product:'Electricity', client:C, department:'Operations',       name:'Masdar Innovation Hub',    ean_code:'971-2-MAS-904200', address:'Masdar City Blk B',      postcode:'00000', city:'Abu Dhabi',      cost_center:'MAS-9042',       status:'Active',  supplier:'ADC',   grid_operator:'ADC',   measurement_company:'ADC Metering',   connection_type:'3x400A LV', building:'Innovation Hub', market_segment:'R&D', monitoring:'Smart', characteristic:'Standard', usage_category:'Laboratory', tax_cluster:'VAT-5' },
  { id:'conn-015', product:'Electricity', client:C, department:'Real Estate',      name:'Sharjah Industrial Zone',  ean_code:'971-6-SHA-771000', address:'Al Sajaa Industrial',    postcode:'00000', city:'Sharjah',        cost_center:'SHA-7710',       status:'Pending', supplier:'SEWA',  grid_operator:'SEWA',  measurement_company:'SEWA Metering',  connection_type:'3x160A LV', building:'Warehouse', market_segment:'Industrial', monitoring:'Traditional', characteristic:'Standard', usage_category:'Warehouse', tax_cluster:'VAT-5' },
  { id:'conn-016', product:'Electricity', client:C, department:'Real Estate',      name:'RAK Free Zone Unit A',     ean_code:'971-7-RAK-331100', address:'RAK FZ Phase 1',         postcode:'00000', city:'Ras Al Khaimah', cost_center:'RAK-7711',       status:'Active',  supplier:'FEWA',  grid_operator:'FEWA',  measurement_company:'FEWA Metering',  connection_type:'3x250A LV', building:'Factory A', market_segment:'Industrial', monitoring:'Traditional', characteristic:'Standard', usage_category:'Manufacturing', tax_cluster:'VAT-5' },
  { id:'conn-017', product:'Electricity', client:C, department:'Real Estate',      name:'Al Reem Island Main',      ean_code:'971-2-REM-210100', address:'Al Reem Island Blvd',    postcode:'00000', city:'Abu Dhabi',      cost_center:'REM-2101',       status:'Active',  supplier:'ADC',   grid_operator:'ADC',   measurement_company:'ADC Metering',   connection_type:'3x160A LV', building:'Residential', market_segment:'Residential', monitoring:'Smart', characteristic:'Standard', usage_category:'Residential', tax_cluster:'VAT-5' },
  { id:'conn-018', product:'Electricity', client:C, department:'Traffic & Roads',  name:'Streetlighting Zone 4',    ean_code:'971-4-BBY-550044', address:'Business Bay Corniche',  postcode:'11211', city:'Dubai',          cost_center:'000-STL-04',     status:'Active',  supplier:'DEWA',  grid_operator:'DEWA',  measurement_company:'DEWA Metering',  connection_type:'1x63A LV',  building:'Street Cabinet', market_segment:'Infrastructure', monitoring:'Basic', characteristic:'Low Load', usage_category:'Lighting',  tax_cluster:'VAT-0' },
  { id:'conn-019', product:'Electricity', client:C, department:'Pumping Stations', name:'Sewage Pump North',        ean_code:'971-4-BBY-993001', address:'Al Khail Rd North',      postcode:'11211', city:'Dubai',          cost_center:'SWG-9930',       status:'Active',  supplier:'DEWA',  grid_operator:'DEWA',  measurement_company:'DEWA Metering',  connection_type:'3x160A LV', building:'Pump House', market_segment:'Utility', monitoring:'Smart', characteristic:'Standard', usage_category:'Sewage',    tax_cluster:'VAT-5' },
  { id:'conn-020', product:'Electricity', client:C, department:'Operations',       name:'Data Centre UPS Feed',     ean_code:'971-4-DIF-770100', address:'DIFC Gate Village 3',    postcode:'50001', city:'Dubai',          cost_center:'DC-7701',        status:'Active',  supplier:'DEWA',  grid_operator:'DEWA',  measurement_company:'DEWA Metering',  connection_type:'3x630A MV', building:'Data Centre', market_segment:'Commercial', monitoring:'Smart', characteristic:'Critical', usage_category:'Data Centre', tax_cluster:'VAT-5' },
  // ── Gas ─────────────────────────────────────────────────────────────────────
  { id:'conn-021', product:'Gas',         client:C, department:'Real Estate',      name:'Masdar City Gas Supply',   ean_code:'971-2-MAS-904110', address:'Masdar City Central',    postcode:'00000', city:'Abu Dhabi',      cost_center:'MAS-GAS-01',     status:'Active',  supplier:'ADNOC', grid_operator:'ADNOC', measurement_company:'ADC Metering',   connection_type:'G100',      building:'HQ Building', market_segment:'Commercial', monitoring:'Smart', characteristic:'Standard', usage_category:'Heating',   tax_cluster:'VAT-5' },
  { id:'conn-022', product:'Gas',         client:C, department:'Operations',       name:'Industrial Gas RAK',       ean_code:'971-7-RAK-GAS-01', address:'RAK FZ Industrial',      postcode:'00000', city:'Ras Al Khaimah', cost_center:'RAK-GAS-01',     status:'Active',  supplier:'FEWA',  grid_operator:'FEWA',  measurement_company:'FEWA Metering',  connection_type:'G250',      building:'Factory A', market_segment:'Industrial', monitoring:'Smart', characteristic:'High Pressure', usage_category:'Process',   tax_cluster:'VAT-5' },
  { id:'conn-023', product:'Gas',         client:C, department:'Real Estate',      name:'DIFC Kitchen Gas',         ean_code:'971-4-DIF-GAS-01', address:'Gate Ave DIFC',          postcode:'50001', city:'Dubai',          cost_center:'DIFC-GAS-01',    status:'Active',  supplier:'DEWA',  grid_operator:'DEWA',  measurement_company:'DEWA Metering',  connection_type:'G16',       building:'F&B Level', market_segment:'Commercial', monitoring:'Smart', characteristic:'Standard', usage_category:'Catering',  tax_cluster:'VAT-5' },
  { id:'conn-024', product:'Gas',         client:C, department:'Facilities',       name:'BBY Heating Plant',        ean_code:'971-4-BBY-GAS-01', address:'Business Bay Basement',  postcode:'11211', city:'Dubai',          cost_center:'FAC-GAS-01',     status:'Inactive',supplier:'DEWA',  grid_operator:'DEWA',  measurement_company:'DEWA Metering',  connection_type:'G25',       building:'Basement Plant', market_segment:'Commercial', monitoring:'Basic', characteristic:'Standard', usage_category:'Heating',   tax_cluster:'VAT-5' },
  // ── Water ────────────────────────────────────────────────────────────────────
  { id:'conn-025', product:'Water',       client:C, department:'Real Estate',      name:'Project Crown Water',      ean_code:'123000000001000150', address:'Spuiboulevard 314',    postcode:'11311', city:'Dubai',          cost_center:'5801009-38005',  status:'Active',  supplier:'DEWA',  grid_operator:'DEWA',  measurement_company:'DEWA Metering',  connection_type:'DN50',      building:'Crown Tower', market_segment:'Commercial', monitoring:'Smart', characteristic:'Standard', usage_category:'Domestic',  tax_cluster:'VAT-0' },
  { id:'conn-026', product:'Water',       client:C, department:'Facilities',       name:'Masdar Irrigation Main',   ean_code:'971-2-MAS-WAT-01',  address:'Masdar City Gardens',  postcode:'00000', city:'Abu Dhabi',      cost_center:'MAS-WAT-01',     status:'Active',  supplier:'ADC',   grid_operator:'ADC',   measurement_company:'ADC Metering',   connection_type:'DN100',     building:'Landscaping', market_segment:'Commercial', monitoring:'Smart', characteristic:'Standard', usage_category:'Irrigation', tax_cluster:'VAT-0' },
]

// Filter option helpers
export const PRODUCTS       = ['Electricity', 'Gas', 'Water'] as const
export const STATUSES       = ['Active', 'Inactive', 'Pending'] as const
export const SUPPLIERS      = [...new Set(FULL_CONNECTIONS.map(c=>c.supplier))]
export const GRID_OPERATORS = [...new Set(FULL_CONNECTIONS.map(c=>c.grid_operator))]
export const MEAS_COMPANIES = [...new Set(FULL_CONNECTIONS.map(c=>c.measurement_company))]
export const CONN_TYPES     = [...new Set(FULL_CONNECTIONS.map(c=>c.connection_type))]
export const DEPARTMENTS    = [...new Set(FULL_CONNECTIONS.map(c=>c.department))]
export const BUILDINGS      = [...new Set(FULL_CONNECTIONS.map(c=>c.building))]
export const MARKET_SEGS    = [...new Set(FULL_CONNECTIONS.map(c=>c.market_segment))]
export const MONITORINGS    = [...new Set(FULL_CONNECTIONS.map(c=>c.monitoring))]
export const CHARACTERISTICS= [...new Set(FULL_CONNECTIONS.map(c=>c.characteristic))]
export const USAGE_CATS     = [...new Set(FULL_CONNECTIONS.map(c=>c.usage_category))]
export const TAX_CLUSTERS   = [...new Set(FULL_CONNECTIONS.map(c=>c.tax_cluster))]
export const CLIENTS        = [...new Set(FULL_CONNECTIONS.map(c=>c.client))]
